### ISSUE TITLE
Print an error message, if i/o dir ist not readable or does not exist.

### ISSUE THREAD

**Issue by dankwart-de** [eilslabs/Roddy#68] opened 2017-06-29 10:01 UTC

**Comment by vinjana** [comment] 2017-09-27 16:21
This is important on clusters with Kerberos protected data directories. Currently, Roddy silently ignores if the I/O directories are not accessible because of permission problems (may be temporary with Kerberos!) or if they don't exist (e.g. due to misconfiguration).

**Comment by vinjana** [comment] 2017-09-29 12:01
Duplicate of #114 .

**Closed by vinjana** 2017-09-29 12:01 UTC
Labels: enhancement
