### ISSUE TITLE
Pass cvalues set / used at workflow execution to jobs via parameter file?

### ISSUE THREAD

**Issue by dankwart-de** [eilslabs/Roddy#99] opened 2017-09-14 11:29 UTC
Might be an interesting question, as we already had several cases, where the developer assumed that values are available when they added them to the config within the execute() method. We could diff the current config / workflow config to the static one and put differences to the parameter file.

**Comment by vinjana** [comment] 2017-09-27 16:30
@dankwart-de 
I am not sure whether I understand the problem. Is this that all parameters, e.g. those given via the Job.run() method should be put into the parameter file? That is implemented now and this issue could be closed.

**Comment by dankwart-de** [comment] 2017-09-28 19:56
I think we already did this, right?

**Comment by vinjana** [comment] 2017-09-29 12:47
O.k. -- as you also cannot identify the exact problem here, I close this now as a duplicate of #105 .

**Closed by vinjana** 2017-09-29 12:47 UTC
Labels: enhancement, question
